[tool.commitizen]
version = "2.0.1"
bump_message = "chore(release): $current_version -> $new_version [skip-ci]"
version_files = [
    "src/VoiceMeeterPlugin/Properties/AssemblyInfo.cs",
    "src/VoiceMeeterPlugin/metadata/LoupedeckPackage.yaml"
]
tag_format = "v$version"